[package]
name = "asninfo"
version = "0.1.0"
edition = "2021"

[dependencies]
bgpkit-commons = "0.7.1"
serde_json = "1"
oneio = { version = "0.17.0", features = ["s3"] }
tracing-subscriber = "0.3"
tracing = "0.1.40"

dotenvy = "0.15.7"